export type WeatherLayersErrorCode =
  | "MANIFEST_FETCH_FAILED"
  | "MANIFEST_INVALID"
  | "ASSET_FETCH_FAILED"
  | "ASSET_DECODE_FAILED"
  | "ASSET_ORIGIN_NOT_ALLOWED"
  | "WEBGL2_UNSUPPORTED"
  | "UNSUPPORTED_PROJECTION"
  | "LAYER_NOT_FOUND"
  | "TIME_NOT_AVAILABLE"
  | "MAP_LAYER_ID_CONFLICT"
  | "CONTROLLER_ALREADY_ATTACHED"
  | "CONTROLLER_DESTROYED";
